spring:
  jackson:
    default-property-inclusion: non_null
logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] [%X{session.id}][%X{request.id}] %-5level %logger{36} - %msg%n"
  level:
    ROOT: ${vcap.services.variable-service.credentials.dwp-api-app-root-loglevel:info}
    uk.gov.dhsc: ${vcap.services.variable-service.credentials.dwp-api-app-loglevel:debug}

server:
  port: 8120
